### PR TITLE
Add `default` argument to Map's value(_)

### PR DESCRIPTION
**Pull request by emrcftci**
# Description

 - Add `default` value as an argument to Map's `value(_)`

We can assign default value effortlessly with this new feature.

# Motivation and Context

 - We will be use `default` argument for assign default value,

 - We will avoid using parentheses for assign default values

 after this pull-request merge.

# What kind of change does this PR introduce?

- [ ]  Bug fix (non-breaking change which fixes an issue)
- [ ]  File changes for improvement
- [x] New feature (non-breaking change which adds functionality)
- [x] This change requires a documentation update
- [x] I have run tests

### CODE REVIEW

**Comment by emrcftci** [comment]
Could you please check? @tristanhimmelman

**Comment by tristanhimmelman** [comment]
I'm ok with this PR, but you will need to rebase master and get the tests passing again in Travis

**Comment by emrcftci** [comment]
> I'm ok with this PR, but you will need to rebase master and get the tests passing again in Travis

I've rebased master into my branch but I accidentally take some commits from my other pull-request(#1081). So I've reverted these unwanted commits. Sorry for the mistake.

**Comment by tristanhimmelman** [comment]
No worries @emrcftci! Thanks for the contributions

**Pull request merged**
